## Benthic Habitat Classification Script (Folk, 1954)
## Requires the interpolated output from 01_interp_sediment.Rda


packages<-c('terra','dplyr')

package.check <- lapply(packages, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})


# 1. Loading Environment and Data ----


# Load the workspace from the interpolation script
sed<-rast('output_data/sediment.tif')
plot(sed)
# The 'sed' object is a SpatRaster containing 'sand', 'mud', and 'gravel' layers.
# We extract them for easier algebraic manipulation.
sand <- sed$sand
mud <- sed$mud
gravel <- sed$gravel


# 2. Raster Math Normalization (100% Assurance) ----
# Ensure no negative values were generated by the interpolation algorithm
sand <- clamp(sand, lower = 0)
mud <- clamp(mud, lower = 0)
gravel <- clamp(gravel, lower = 0)

# Calculate the total sum per pixel
total_sum <- sand + mud + gravel
plot(total_sum)
# Normalize each fraction to strictly sum up to 100%
sand_norm <- (sand / total_sum) * 100
mud_norm <- (mud / total_sum) * 100
gravel_norm <- (gravel / total_sum) * 100

sed<-c(sand_norm,mud_norm,gravel_norm)
writeRaster(sed,'output_data/sediment_norm.tif')

# 3. Calculate Sand/Mud Ratio (Diagram X-Axis) ----
# Summing normalized sand and mud
sum_sand_mud <- sand_norm + mud_norm

# Calculate the relative percentage of sand in the sand-mud fraction
# We use ifel to avoid division by zero in pixels that are 100% gravel
sand_ratio <- ifel(sum_sand_mud == 0, 0, (sand_norm / sum_sand_mud) * 100)
plot(sand_ratio)

# 4. Apply Folk Boundaries (11 Classes) ----
# Structuring the ifel() statements respecting the 4 "tiers" of the Folk diagram

folk_classes <- 
  
  # --- TIER 1: > 80% Gravel ---
  ifel(gravel_norm >= 80, 1, # Gravel (G)
       
       # --- TIER 2: 30% to 80% Gravel ---
       ifel(gravel_norm >= 30 & gravel_norm < 80 & sand_ratio >= 50, 2, # Sandy Gravel (sG)
            ifel(gravel_norm >= 30 & gravel_norm < 80 & sand_ratio >= 10 & sand_ratio < 50, 3, # Muddy Sandy Gravel (msG)
                 ifel(gravel_norm >= 30 & gravel_norm < 80 & sand_ratio < 10, 4, # Muddy Gravel (mG)
                      
                      # --- TIER 3: 5% to 30% Gravel ---
                      ifel(gravel_norm >= 5 & gravel_norm < 30 & sand_ratio >= 90, 5, # Gravelly Sand (gS)
                           ifel(gravel_norm >= 5 & gravel_norm < 30 & sand_ratio >= 10 & sand_ratio < 90, 6, # Gravelly Muddy Sand (gmS)
                                ifel(gravel_norm >= 5 & gravel_norm < 30 & sand_ratio < 10, 7, # Gravelly Mud (gM)
                                     
                                     # --- TIER 4: < 5% Gravel ---
                                     ifel(gravel_norm < 5 & sand_ratio >= 90, 8, # Sand (S)
                                          ifel(gravel_norm < 5 & sand_ratio >= 50 & sand_ratio < 90, 9, # Muddy Sand (mS)
                                               ifel(gravel_norm < 5 & sand_ratio >= 10 & sand_ratio < 50, 10, # Sandy Mud (sM)
                                                    ifel(gravel_norm < 5 & sand_ratio < 10, 11, # Mud (M)
                                                         
                                                         NA ))))))))))) # Close all parentheses. Anything left over becomes NA.


# 5. Convert to Categorical Raster (Metadata) ----
# Notifying the terra package that this is categorical data
folk_classes <- as.factor(folk_classes)

# Creating the Raster Attribute Table (RAT)
folk_table <- data.frame(
  ID = 1:11,
  Habitat = c(
    "Gravel", 
    "Sandy Gravel", 
    "Muddy Sandy Gravel", 
    "Muddy Gravel", 
    "Gravelly Sand", 
    "Gravelly Muddy Sand", 
    "Gravelly Mud", 
    "Sand", 
    "Muddy Sand", 
    "Sandy Mud", 
    "Mud"
  )
)

# Applying the names to the raster
levels(folk_classes) <- folk_table

# Visualization
plot(folk_classes, main = "Benthic Habitats (Folk, 1954)")

# 6. Export Final Raster ----
# Writing the GeoTIFF with the embedded attribute table for QGIS mapping
writeRaster(folk_classes, 'output_data/folk_classification.tif', overwrite = TRUE)
