## Benthic Habitat Classification Script (Simplified Folk 5-Class)
## Requires the interpolated output from 01_interp_sediment.Rda

packages <- c('terra', 'dplyr')

package.check <- lapply(packages, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})

# 1. Loading Environment and Data ----
# Load the workspace from the interpolation script
sed <- rast('output_data/sediment.tif')
plot(sed)

# The 'sed' object is a SpatRaster containing 'sand', 'mud', and 'gravel' layers.
# We extract them for easier algebraic manipulation.
sand <- sed$sand
mud <- sed$mud
gravel <- sed$gravel


# 2. Raster Math Normalization (100% Assurance) ----
# Ensure no negative values were generated by the interpolation algorithm
sand <- clamp(sand, lower = 0)
mud <- clamp(mud, lower = 0)
gravel <- clamp(gravel, lower = 0)

# Calculate the total sum per pixel
total_sum <- sand + mud + gravel
plot(total_sum, main = "Total Sum Before Normalization")

# Normalize each fraction to strictly sum up to 100%
sand_norm <- (sand / total_sum) * 100
mud_norm <- (mud / total_sum) * 100
gravel_norm <- (gravel / total_sum) * 100

sed_norm <- c(sand_norm, mud_norm, gravel_norm)

writeRaster(sed_norm, 'output_data/sediment_norm.tif', overwrite = TRUE)


# 3. Calculate Sand/Mud Ratio (Diagram X-Axis) ----
# Summing normalized sand and mud
sum_sand_mud <- sand_norm + mud_norm

# Calculate the relative percentage of sand in the sand-mud fraction
# We use ifel to avoid division by zero in pixels that are 100% gravel
sand_ratio <- ifel(sum_sand_mud == 0, 0, (sand_norm / sum_sand_mud) * 100)
plot(sand_ratio, main = "Sand Ratio (%)")


# 4. Apply Simplified Folk Boundaries (5 Classes) ----
# Structuring the ifel() statements into 5 major textural domains

folk_classes <- 
  
  # --- TIER 1: > 30% Gravel ---
  ifel(gravel_norm >= 30, 1, # Gravels (G, sG, mG, msG)
       
       # --- TIER 2: 5% to 30% Gravel ---
       ifel(gravel_norm >= 5 & gravel_norm < 30, 2, # Gravelly Sediments (gS, gmS, gM)
            
            # --- TIER 3: < 5% Gravel, Sand-Dominated ---
            ifel(gravel_norm < 5 & sand_ratio >= 90, 3, # Sand (S)
                 
                 # --- TIER 4: < 5% Gravel, Mixed Sand & Mud ---
                 ifel(gravel_norm < 5 & sand_ratio >= 10 & sand_ratio < 90, 4, # Mixed Sand-Mud (mS, sM)
                      
                      # --- TIER 5: < 5% Gravel, Mud-Dominated ---
                      ifel(gravel_norm < 5 & sand_ratio < 10, 5, # Mud (M)
                           
                           NA ))))) # Close all parentheses. Anything left over becomes NA.


# 5. Convert to Categorical Raster (Metadata) ----
# Notifying the terra package that this is categorical data
folk_classes <- as.factor(folk_classes)

# Creating the Raster Attribute Table (RAT) for the 5 classes
folk_table <- data.frame(
  ID = 1:5,
  Habitat = c(
    "Gravel", 
    "Gravelly Sediment", 
    "Sand", 
    "Mixed Sand-Mud", 
    "Mud"
  )
)

# Applying the names to the raster
levels(folk_classes) <- folk_table

# 6. Defining the Standard Folk Color Palette ----
# Colors are sampled directly from the provided ternary diagram reference.
folk_color_table <- data.frame(
  value = 1:5,
  color = c(
    "#B95246",  # 1: Gravel (Coarse sediment - Reddish Brown)
    "#C68F8A",  # 2: Gravelly Sediment (Mixed sediment - Mauve/Dusty Pink)
    "#FCE47F",  # 3: Sand (Yellow)
    "#9EB25C",  # 4: Mixed Sand-Mud (Olive Green)
    "#4A7A40"   # 5: Mud (Dark Green)
  )
)


# Embed the standard colors directly into the SpatRaster metadata
coltab(folk_classes) <- folk_color_table

# Visualization
jpeg(filename = "figures/sediment_folk_5class.jpg", 
     width = 18,       # Width of the image
     height = 17,       # Height of the image
     units = "cm",     # Units for width/height (inches)
     res = 300)        # Resolution in pixels per inch
plot(folk_classes, main = "Sediment Folk (5-Class)")
dev.off()


# 7. Export Final Raster ----
# Writing the GeoTIFF with the embedded attribute table for QGIS mapping
writeRaster(folk_classes, 'output_data/folk_classification_5classes.tif', overwrite = TRUE)
