## Benthic Habitat Classification Script (Simplified Folk 5-Class)
## Requires the interpolated output from 01_interp_sediment.Rda

packages <- c('terra', 'dplyr','sf')

package.check <- lapply(packages, FUN = function(x) {
  if (!require(x, character.only = TRUE)) {
    install.packages(x, dependencies = TRUE)
    library(x, character.only = TRUE)
  }
})

# 1. Loading Environment and Data ----
# Load the workspace from the interpolation script
sed <- rast('output_data/sediment.tif')
plot(sed)

# The 'sed' object is a SpatRaster containing 'sand', 'mud', and 'gravel' layers.
# We extract them for easier algebraic manipulation.
sand <- sed$sand
mud <- sed$mud
gravel <- sed$gravel


# 2. Raster Math Normalization (100% Assurance) ----
# Ensure no negative values were generated by the interpolation algorithm
sand <- clamp(sand, lower = 0)
mud <- clamp(mud, lower = 0)
gravel <- clamp(gravel, lower = 0)

# Calculate the total sum per pixel
total_sum <- sand + mud + gravel
plot(total_sum, main = "Total Sum Before Normalization")

# Normalize each fraction to strictly sum up to 100%
sand_norm <- (sand / total_sum) * 100
mud_norm <- (mud / total_sum) * 100
gravel_norm <- (gravel / total_sum) * 100

sed_norm <- c(sand_norm, mud_norm, gravel_norm)

writeRaster(sed_norm, 'output_data/l0_sediment_norm.tif', overwrite = TRUE)


# 3. Calculate Sand/Mud Ratio (Diagram X-Axis) ----
# Summing normalized sand and mud
sum_sand_mud <- sand_norm + mud_norm

# Calculate the relative percentage of sand in the sand-mud fraction
# We use ifel to avoid division by zero in pixels that are 100% gravel
sand_ratio <- ifel(sum_sand_mud == 0, 0, (sand_norm / sum_sand_mud) * 100)
plot(sand_ratio, main = "Sand Ratio (%)")

## 3.1. Biogenic ----
mask<-rast('input_data/eez_albers.tif')

bio<-read_sf('input_data/biogenico.shp')
bio<-st_set_crs(bio,4326)
bio<-st_transform(bio,crs(mask))

bio <- rasterize(bio, mask, field = 1)

bio<-subst(bio, from=NA, to=0)
bio<-mask(bio,mask)
plot(bio)

writeRaster(bio, 'input_data/biogenico.tif')

# 4. Apply Simplified Boundaries with Binary Biogenic Tier (4 Classes) ----
# Tier 0 intercepts any pixel where the biogenic flag is 1 (True).

# (Assumindo que você carregou o raster binário como 'bio' na etapa 1)
folk_classes <- 
  
  # --- TIER 0: Biogenic (Binary flag == 1) ---
  ifel(bio == 1, 4, 
       
       # --- TIER 1: >= 5% Gravel ---
       ifel(gravel_norm >= 5, 3, 
            
            # --- TIER 2: < 5% Gravel, Mud:Sand ratio > 9:1 (Sand < 10%) ---
            ifel(gravel_norm < 5 & sand_ratio < 10, 1, 
                 
                 # --- TIER 3: < 5% Gravel, Mud:Sand ratio <= 9:1 (Sand >= 10%) ---
                 ifel(gravel_norm < 5 & sand_ratio >= 10, 2, 
                      
                      NA )))) # Close all parentheses.

writeRaster(folk_classes,
            'output_data/l0_sediment_folk_4.tif',
            overwrite=T)
hist(folk_classes)
# 5. Convert to Categorical Raster (Metadata) ----
folk_classes <- as.factor(folk_classes)

# Creating the Raster Attribute Table (RAT)
folk_table <- data.frame(
  ID = 1:4,
  Habitat = c(
    "Muddy", 
    "Sandy",  
    "Gravel",
    "Biogenic"
  )
)

# Applying the names to the raster
levels(folk_classes) <- folk_table



# 6. Apply Colors and Export ----
folk_color_table <- data.frame(
  value = 1:4,
  color = c(
    "#4A7A40", # 1: Muddy (Dark Green)
    "#FCE47F",  # 2: Sandy (Yellow)
    "#B95246", # 3: Gravel (Reddish Brown)
    "#DDA0DD" # 4: Biogenic (Plum / Light Purple)
  )
)

coltab(folk_classes) <- folk_color_table
# Visualization

jpeg(filename = "figures/l0_sediment_folk_4class.jpg", 
     width = 40,       # Width of the image
     height = 50,       # Height of the image
     units = "cm",     # Units for width/height (inches)
     res = 300)        # Resolution in pixels per inch
plot(folk_classes, main = "Sediments (Biogenic + 3 Class Folk)",
     mar = c(3, 3, 3, 25),
     cex.main = 3,
     plg = list(cex = 2))
dev.off()


writeRaster(folk_classes, 
            'output_data/l0_folk_classification_biogenic4.tif', 
            overwrite = TRUE)
